# Generated by Django 3.1.4 on 2021-01-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_pelicula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='imagen',
            new_name='imagen_fondo',
        ),
    ]
