# Generated by Django 3.1.4 on 2021-01-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210112_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='Director de la Pelicula'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen_fondo',
            field=models.ImageField(upload_to='fondos_peliculas'),
        ),
    ]
