# Generated by Django 3.1.4 on 2021-01-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210112_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='descripcion',
        ),
    ]
