# Generated by Django 3.1.4 on 2021-01-13 01:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_pelicula_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
