# Generated by Django 3.1.4 on 2021-01-13 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_pelicula_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='anio',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)], verbose_name='Año de la Pelicula'),
        ),
    ]
